language: python
python:
  - "3.9"
install:
  - pip install coveralls pytest-cov
  - pip install redis
  - pip install .
script:
  - python -m pytest examples
  - pytest --cov=millet
services:
  - redis-server
after_success:
  - coveralls
